# Site settings
title: Jallunvalajat
email: jallunvalajat@gmail.com
description: "Jallunvalajat ry on yhden tähden asiaton järjestö, jonka tehtävä on ajaa jäsentensä etua sekä varjella perinteistä suomalaista kulttuuria niin valtionmonopoleissa, ravitsemusliikkeissä kuin etelän kaukomaillakin."
baseurl: ""
url: "http://jallunvalajat.github.io"
twitter_username: Jallunvalajat
facebook_username:  Jallunvalajat

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Prose.io
prose:
    rooturl: "_posts"
    siteurl: "http://jallunvalajat.github.io"
    media: "img"
    metadata:
        _posts:
            - name: "layout"
            field:
                element: "hidden"
                value: "post"
            - name: "title"
            field:
                element: "text"
                label: "otsikko"
            - name: "subtitle"
            field:
                element: "text"
                label: "alaotsikko"
            - name: "categories"
            field:
                element: "select"
                label: "kategoria"
                options:
                    - name: "Uutinen"
                    value: "uutiset"
                    - name: "Tapahtuma"
                    value: "tapahtuma"

