# Site settings
title: Jallunvalajat
email: jallunvalajat@gmail.com
description: "Jallunvalajat ry on yhden tähden asiaton järjestö, jonka tehtävä on ajaa jäsentensä etua sekä varjella perinteistä suomalaista kulttuuria niin valtionmonopoleissa, ravitsemusliikkeissä kuin etelän kaukomaillakin."
baseurl: ""
url: "http://jallunvalajat.github.io"
# twitter_username: Jallunvalajat
facebook_username:  Jallunvalajat
instagram_username:  Jallunvalajat

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Prose.io
prose:
    rooturl: "_posts"
    siteurl: "http://jallunvalajat.github.io"
    media: "img"
